connectionReferences:
  - connectionReferenceLogicalName: intx_intelligentpatientintaketriageassistant_16e55f.cr.shared_intx-5fverify.eb1ac389c6194ac42439202
    connectorId: /providers/Microsoft.PowerApps/apis/shared_intx-5fverify-20insurance-20mcp-5f46f18f33b2ee8a8d
