connectionReferences:
  - connectionReferenceLogicalName: clinx_clinicaldocumentationcodingassistant_0a1ba9.cr.shared_clinx-5flog-2.09efd9038a2e568f299547911
    connectorId: /providers/Microsoft.PowerApps/apis/shared_clinx-5flog-20compliance-20audit-20mcp-5f46f18f33b2ee8a8d
